# List without repetitions from: http://listofrandomnames.com/index.cfm?generated
from random import randint
repetition_frequencies = [1,1,1,1,1,2,2,2,3,4]
rnames = ['Gretta Swigert',
    'Kit Priolo',
    'Latonia Visconti',
    'Marcelino Spikes',
    'Monroe Russo',
    'Katharina Ellwood',
    'Sherrie Bailon',
    'Daisy Lundgreen',
    'Dominica Longmire',
    'Von Geraghty',
    'Harlan Rochelle',
    'Cathrine Mumford',
    'Terrell Dunigan',
    'Monserrate Kimery',
    'Siu Hanel',
    'Bong Lasky',
    'Janeth Jacome',
    'Errol Sines',
    'Mandie Grim',
    'Ernestina Kerner',
    'Leatrice Gonsoulin',
    'Shani Teel',
    'Nicol Bradsher',
    'Lorri Beaver',
    'Taryn Linnell',
    'Bridget Durrah',
    'Casandra Brisbin',
    'Lanelle Mandel',
    'Arlen Waage',
    'Emily Briggs',
    'Narcisa Farias',
    'Spencer Milstead',
    'Deeanna Sica',
    'Twana Shen',
    'Loree Pounders',
    'Vincenzo Brumsey',
    'Sal Pulliam',
    'Tabatha Silvers',
    'Temeka Koury',
    'Jeffrey Stgelais',
    'Jarvis Kober',
    'Fermin Meyerhoff',
    'Chelsea Burger',
    'Bobette Burnett',
    'Georgiana Sieck',
    'Tawny Yerger',
    'Mayola Trombly',
    'Zenia Horan',
    'Caroll Nimmo',
    'Johnson Ryberg']

for name in rnames:
	rint = randint(0,len(repetition_frequencies) - 1)
	freq = repetition_frequencies[rint]
	for i in range(freq):
		print(name)